name: Build Yocto

on:
  workflow_dispatch:
    inputs:
      yoctoBranch: 
        description: 'Yocto Branch To Use For Build'
        default: 'dunfell'
        required: true
        type: string

env:
  YOCTO_SOURCE: ''

jobs:
  build:
    name: Build RPi Yocto Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Required Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping libsdl1.2-dev xterm
          sudo locale-gen en_US.UTF-8

      - name: Clone Yocto Repository
        run: git clone -b ${{ inputs.yoctoBranch }} --single-branch git://git.yoctoproject.org/poky yocto

      - name: Setup Yocto Environment
        run: source yocto/oe-init-build-env

      - name: Build Raspberry Pi Image
        run: |
          ls build/
          source yocto/oe-init-build-env
          bitbake rpi-basic-image

      - name: Archive Artifact
        uses: actions/upload-artifact@v2
        with:
          name: yocto-rpi-image
          path: yocto/build/tmp/deploy/images/raspberrypi
